##  AutoAIデータ作成用

In [2]:
# 共通事前処理

# 必要ライブラリのimport
import pandas as pd
# データフレーム表示用関数
from IPython.display import display

In [3]:
# 公開データのダウンロードと解凍
!wget https://archive.ics.uci.edu/ml/\
machine-learning-databases/00222/bank.zip -O bank.zip | tail -n 1
!unzip -o bank.zip | tail -n 1

# bank-full.csvをデータフレームに取り込み
df_all = pd.read_csv('bank-full.csv', sep=';')

# 項目名を日本語に置き換える
columns = [
    '年齢', '職業', '婚姻', '学歴', '債務不履行',  '平均残高',  '住宅ローン',  '個人ローン',
    '連絡手段',  '最終通話日',  '最終通話月',  '最終通話秒数', '通話回数_販促中',
    '前回販促後_経過日数',  '通話回数_販促前',  '前回販促結果', '今回販促結果'
]
df_all.columns = columns

--2020-06-26 12:47:46--  https://archive.ics.uci.edu/ml/
archive.ics.uci.edu (archive.ics.uci.edu) をDNSに問いあわせています... 128.195.10.252
archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443 に接続しています... 接続しました。
HTTP による接続要求を送信しました、応答を待っています... 200 OK
長さ: 54 [text/html]
`bank.zip' に保存中

bank.zip            100%[===================>]      54  --.-KB/s 時間 0s

2020-06-26 12:47:47 (713 KB/s) - `bank.zip' へ保存完了 [54/54]

--2020-06-26 12:47:47--  http://machine-learning-databases/00222/bank.zip
machine-learning-databases (machine-learning-databases) をDNSに問いあわせています... 失敗しました: nodename nor servname provided, or not known.
wget: ホストアドレス `machine-learning-databases' を解決できませんでした。
終了しました --2020-06-26 12:47:47--
経過時間: 0.6s
ダウンロード完了: 1 ファイル、54 バイトを 0s で取得 (713 KB/s)
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of bank.zip or
        bank.zip.zip, and cannot find bank.zip.ZIP, period.
Archive:  bank.zip

In [4]:
display(df_all.head())

,年齢,職業,婚姻,学歴,債務不履行,平均残高,住宅ローン,個人ローン,連絡手段,最終通話日,最終通話月,最終通話秒数,通話回数_販促中,前回販促後_経過日数,通話回数_販促前,前回販促結果,今回販促結果
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [5]:
# CSV export
fn = 'bank-autoai.csv'
df_all.to_csv(fn, index=False)

In [ ]:
# Google Colab からPCにダウンロード
from google.colab import files
files.download(fn)